//Chapter

export const SET_CHAPTER_LOADER = "SET_CHAPTER_LOADER";
//get_all

export const GET_ALL_CHAPTER_SUCCESS = "GET_ALL_CHAPTER_SUCCESS";
export const GET_ALL_CHAPTER_ERROR = "GET_ALL_CHAPTER_ERROR";
//get

export const GET_CHAPTER_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_CHAPTER_ERROR = "GET_CHAPTER_ERROR";
//post

export const POST_CHAPTER_SUCCESS = "POST_CHAPTER_SUCCESS";
export const POST_CHAPTER_ERROR = "POST_CHAPTER_ERROR";
//delete

export const DELETE_CHAPTER_SUCCESS = "DELETE_CHAPTER_SUCCESS";
export const DELETE_CHAPTER_ERROR = "DELETE_CHAPTER_ERROR";
//Put

export const PUT_CHAPTER_SUCCESS = "PUT_CHAPTER_SUCCESS";
export const PUT_CHAPTER_ERROR = "PUT_CHAPTER_ERROR";

//DEVICE
export const GET_DEVICE_LOADER = "GET_DEVICE_LOADER";
export const GET_ALL_DEVICE_SUCCESS = "GET_ALL_DEVICE_SUCCESS";
export const GET_ALL_DEVICE_ERROR = "GET_ALL_DEVICE_ERROR";

//get

export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
export const GET_DEVICE_ERROR = "GET_DEVICE_ERROR";

//quiz
export const GET_QUIZ_LOADER = "GET_CHAPTER_LOADER";
export const GET_QUIZ_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_QUIZ_ERROR = "GET_CHAPTER_ERROR";

//session
export const GET_ALL_SESSION_SUCCESS = "GET_ALL_SESSION_SUCCESS";
export const POST_SESSION_LOADER = "POST_SESSION_LOADER";
export const POST_SESSION_SUCCESS = "POST_SESSION_SUCCESS";
export const POST_SESSION_ERROR = "POST_SESSION_ERROR";

export const PUT_SESSION_SUCCESS = 'PUT_SESSION_SUCCESS';
export const PUT_SESSION_ERROR = 'PUT_SESSION_ERROR'

//subject
export const SUBJECT_LOADER = "SUBJECT_LOADER";
//get_all
export const GET_ALL_SUBJECT_SUCCESS = "GET_ALL_SUBJECT_SUCCESS";
export const GET_ALL_SUBJECT_ERROR = "GET_ALL_SUBJECT_ERROR";
//get
export const GET_SUBJECT_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_SUBJECT_ERROR = "GET_CHAPTER_ERROR";
//post
export const POST_SUBJECT_SUCCESS = "POST_SUBJECT_SUCCESS";
export const POST_SUBJECT_LOADER = "POST_SUBJECT_LOADER";
export const POST_SUBJECT_ERROR = "POST_SUBJECT_ERROR";
//delete
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_ERROR = "DELETE_SUBJECT_ERROR";
//put
export const PUT_SUBJECT_SUCCESS = "PUT_SUBJECT_SUCCESS";
export const PUT_SUBJECT_ERROR = "PUT_SUBJECT_ERROR";

//tOPIC
export const GET_ALL_TOPIC_LOADER = "GET_ALL_TOPIC_LOADER";
export const GET_ALL_TOPIC_SUCCESS = "GET_ALL_TOPIC_SUCCESS";
export const GET_ALL_TOPIC_ERROR = "GET_ALL_TOPIC_ERROR";
//get
export const GET_TOPIC_LOADER = "GET_TOPIC_LOADER";
export const GET_TOPIC_SUCCESS = "GET_TOPIC_SUCCESS";
export const GET_TOPIC_ERROR = "GET_TOPIC_ERROR";
//post
export const POST_TOPIC_LOADER = "POST_TOPIC_LOADER";
export const POST_TOPIC_SUCCESS = "POST_TOPIC_SUCCESS";
export const POST_TOPIC_ERROR = "POST_TOPIC_ERROR";

//socket
export const SET_SOCKET_URL = 'SET_SOCKET_URL'

